<div align="center"><h3>HW3, Question 2</h3></div>
<div align="center"><h5>Mohammadreza Ghofrani, 400131076</h5></div>

In [1]:
import scipy
import sklearn
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn import *
import plotly.express as px
import plotly.graph_objects as go

pd.options.plotting.backend = "plotly"

# Initialization

Loading the dataset

In [2]:
train = pd.read_csv('data/data_train.csv', header=None)
test = pd.read_csv('data/data_test.csv', header=None)

Global constants

In [3]:
LABLE_COLUMN = 16

# Part A

Training the random forest

In [4]:
random_forest = list()
features = list(train.columns)
features.remove(LABLE_COLUMN)
for i in range(15):
    f1, f2, f3 = np.random.choice(features, 3, replace=False)
    tree_clf = sklearn.tree.DecisionTreeClassifier(max_depth=3)
    tree_clf.fit(train[[f1,f2,f3]], train[LABLE_COLUMN])
    random_forest.append((tree_clf, (f1,f2,f3)))

Testing random forest

In [5]:
# True Lables
y_true = list()
y_true = test[LABLE_COLUMN]

# Predicting using Random Forest
voting_box = np.zeros((len(test), len(set(y_true))))
for clf, features in random_forest:
    clf_prediction = clf.predict(test[list(features)])
    for i, p in enumerate(clf_prediction):
        voting_box[i][p] += 1
y_pred = list()
for instance in voting_box:
    y_pred.append(np.argmax(instance))

print(f"\t\t\tRandom Forest Classifier Results")
print(f"Accuracy: {sklearn.metrics.accuracy_score(y_true, y_pred):.4f}")
print(f"Precision: {sklearn.metrics.precision_score(y_true, y_pred, average='macro'):.4f}")
print(f"Confusion Matrix:\n {sklearn.metrics.confusion_matrix(y_true, y_pred)}")

			Random Forest Classifier Results
Accuracy: 0.6481
Precision: 0.6643
Confusion Matrix:
 [[307   0  12   0   3   0  41   0   0   0]
 [  0 133 128  94   7   0   1   1   0   0]
 [  0   1 333  27   1   0   0   2   0   0]
 [  0   3   0 332   1   0   0   0   0   0]
 [  0   0   3  10 350   0   1   0   0   0]
 [  1   0   2 163   2 166   0   0   1   0]
 [  2   0   1   2   0   0 328   3   0   0]
 [  0  22  11  19  28   3  34 246   1   0]
 [ 69   0  15   1   0  80  96   3  72   0]
 [  0   8   0 262  63   0   2   0   1   0]]


/home/engmrgh/university/1th_semester/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Part B

In [13]:
random_forest = sklearn.ensemble.RandomForestClassifier(n_estimators=15, max_depth=3, random_state=0, max_features=3)

In [ ]:
y_pred = clf.predict(test.loc[:, test.columns != LABLE_COLUMN])

Training Adaboost classifier

In [6]:
clf = sklearn.ensemble.AdaBoostClassifier(n_estimators=10)
clf.fit(train.loc[:, train.columns != LABLE_COLUMN], train[LABLE_COLUMN])

AdaBoostClassifier(n_estimators=10)

Testing the classifier

In [7]:
y_true = test[LABLE_COLUMN]
y_pred = clf.predict(test.loc[:, test.columns != LABLE_COLUMN])

print(f"\t\t\tAdaboost Tree Classifier Results")
print(f"Accuracy: {sklearn.metrics.accuracy_score(y_true, y_pred):.4f}")
print(f"Precision: {sklearn.metrics.precision_score(y_true, y_pred, average='macro'):.4f}")
print(f"Confusion Matrix:\n {sklearn.metrics.confusion_matrix(y_true, y_pred)}")

			Adaboost Tree Classifier Results
Accuracy: 0.5486
Precision: 0.6366
Confusion Matrix:
 [[298   0   1   0   0   0  62   2   0   0]
 [  0 215 143   0   0   0   1   1   0   4]
 [  0   8 330   4   0   0  13   8   0   1]
 [  0   2 328   4   0   0   0   1   0   1]
 [  0   0   0   0 327   0  18   0   0  19]
 [  7   5  75  48   2   4  31 132   0  31]
 [  1   0   8   0   1   0 313  11   0   2]
 [  0  31  12   2   0   0   0 297   0  22]
 [ 59   0   1   0   0   1 104 150  21   0]
 [  0  13 186  12  12   0   2   1   0 110]]


# Part C

Training with 5, 20 and 50 classifiers and reporting the result.

In [8]:
for n_estimators in [5, 20, 50]:
    clf = sklearn.ensemble.AdaBoostClassifier(n_estimators=n_estimators)
    clf.fit(train.loc[:, train.columns != LABLE_COLUMN], train[LABLE_COLUMN])
    y_true = test[LABLE_COLUMN]
    y_pred = clf.predict(test.loc[:, test.columns != LABLE_COLUMN])

    print(f"\t\t\tAdaboost Tree Classifier Results with {n_estimators} number of estimators")
    print(f"Accuracy: {sklearn.metrics.accuracy_score(y_true, y_pred):.4f}")
    print(f"Precision: {sklearn.metrics.precision_score(y_true, y_pred, average='macro'):.4f}")
    print(f"Confusion Matrix:\n {sklearn.metrics.confusion_matrix(y_true, y_pred)}")
    print()

			Adaboost Tree Classifier Results with 5 number of estimators
Accuracy: 0.5234
Precision: 0.5487
Confusion Matrix:
 [[328   0   1   1   1   0  25   0   7   0]
 [  0 135 216   3   9   0   1   0   0   0]
 [  0   0 338   5   0   0  13   8   0   0]
 [  0   2 329   4   0   0   0   0   0   1]
 [  0   5   0   3 336   0  18   0   0   2]
 [166   5  75  84   3   0   0   0   1   1]
 [  9   0   8   5   5   0 297  12   0   0]
 [  3  57  17   5  23   0   0 250   5   4]
 [165   0   2   0   1   0   1  63 104   0]
 [  0  33 188  41  34   0   0   0   1  39]]

			Adaboost Tree Classifier Results with 20 number of estimators
Accuracy: 0.6369
Precision: 0.6388
Confusion Matrix:
 [[323   0   1   0   1   0  26   0  12   0]
 [  0 207 138   5   0   0   2   0   0  12]
 [  0   8 334   1   0   0  13   8   0   0]
 [  0   2  60 245   0  19   9   0   0   1]
 [  1   9   3   0 324   0  19   0   0   8]
 [165  12   0 119   2  11  15   1   2   8]
 [  0   0   0   8   0   0 320   5   1   2]
 [  0  31  12   2   0   0   9 

/home/engmrgh/university/1th_semester/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


			Adaboost Tree Classifier Results with 50 number of estimators
Accuracy: 0.6103
Precision: 0.5906
Confusion Matrix:
 [[336   0   1   0   0   0  23   0   3   0]
 [  0 212 138   5   4   0   2   0   0   3]
 [  0   8 334   1   0   0  13   8   0   0]
 [  0   2  60 245   0  19   9   0   0   1]
 [  1   9   3   0 325   0  19   0   0   7]
 [166  12   0 119   2  11  15   0   2   8]
 [  0   0   0   8   0   0 308   5  13   2]
 [  0  31  12   2   0   0   9 270  18  22]
 [264   0  10   0   0   0  12  28  22   0]
 [  1  24   9 168  12  30  20   0   0  72]]



# Part D

In [9]:
dtrain = xgb.DMatrix(train.iloc[:, train.columns!=LABLE_COLUMN], label=train[LABLE_COLUMN])
dtest = xgb.DMatrix(test.iloc[:, test.columns!=LABLE_COLUMN], label=test[LABLE_COLUMN])

estimator = xgb.XGBClassifier(objective= 'multi:softmax', nthread=4, use_label_encoder=False, eval_metric='mlogloss')

parameters = {
    'max_depth': range (2, 10, 2),
    'n_estimators': range(10, 30, 10),
    'learning_rate': [0.1, 0.01, 0.001],
    'min_split_loss': range(1, 10, 3),
    'max_depth': range(3, 10, 2)
}

grid_search = sklearn.model_selection.GridSearchCV(estimator=estimator, param_grid=parameters, n_jobs = 5)
grid_search.fit(train.loc[:, train.columns != LABLE_COLUMN], train[LABLE_COLUMN])

Fitting 5 folds for each of 72 candidates, totalling 360 fits


GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     enable_categorical=False,
                                     eval_metric='mlogloss', gamma=None,
                                     gpu_id=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone...
                                     num_parallel_tree=None,
                                     objective='multi:softmax', predictor=None,
                                     random_state=None, reg_alpha=None,
                                     reg_lambda

In [10]:
best_estimator = grid_search.best_estimator_
best_estimator.fit(train.loc[:, train.columns != LABLE_COLUMN], train[LABLE_COLUMN])
y_true = test[LABLE_COLUMN]
y_pred = best_estimator.predict(test.loc[:, test.columns != LABLE_COLUMN])

print(f"\t\t\tXG Boost Results")
print(f"Accuracy: {sklearn.metrics.accuracy_score(y_true, y_pred):.4f}")
print(f"Precision: {sklearn.metrics.precision_score(y_true, y_pred, average='macro'):.4f}")
print(f"Confusion Matrix:\n {sklearn.metrics.confusion_matrix(y_true, y_pred)}")
print()

			XG Boost Results
Accuracy: 0.9443
Precision: 0.9454
Confusion Matrix:
 [[342   1   0   0   0   0   0   0  20   0]
 [  0 321  40   0   0   0   0   2   0   1]
 [  0   4 354   3   0   0   1   2   0   0]
 [  0   4   0 330   0   0   0   1   0   1]
 [  0   2   0   0 357   4   0   0   0   1]
 [  0   0   0   7   0 288   1   0   3  36]
 [  0   1   0   0   0   4 331   0   0   0]
 [  0  10   1   3  16   0   1 333   0   0]
 [  1   0   0   0   0   0   0   0 335   0]
 [  0   6   0   9   0   6   0   2   1 312]]

